Module2 task1
htmlacademy-adaptive/2056523-sedona-26 pull request #2
Opened 2022-08-01 07:08 UTC by Gri-F

2022-08-01 18:00 UTC, andreysgra requested changes
На странице формы нужно разметить эти блоки:
![image](https://user-images.githubusercontent.com/17790771/182210878-bcf07b42-fb84-433e-b621-cbc11321b6b0.png)
![image](https://user-images.githubusercontent.com/17790771/182211353-888e5094-f916-4f12-8eff-0430045c6be4.png)

Главную страницу проверь в сервисе проверки именования классов по БЭМ: https://yoksel.github.io/html-tree/. Очень много ошибок.

2022-08-01 18:00 UTC, andreysgra commented on source/catalog.html
> +            <a href="#">Главная</a>
Ссылка на главную страницу.

2022-08-01 18:00 UTC, andreysgra commented on source/catalog.html
> +            <a href="#">Фото и видео</a>
Здесь либо ссылка на себя, то есть catalog.html, либо атрибут `href` нужно убрать, но якорь `#` использовать здесь однозначно не стоит.

2022-08-01 18:00 UTC, andreysgra commented on source/catalog.html
> +            <a href="#">Форма отзыва</a>
Ссылка на страницу формы.

2022-08-01 18:00 UTC, andreysgra commented on source/catalog.html
> +          <li class="site-list__item site-list__item--active">
1. Почему у каждого элемента списка есть класс `site-list__item--active`?
2. Интерактивным элементом с которым взаимодействует пользователь является ссылка, а не элемент списка. Значит все стили, которые будут изменяться при взаимодействии, вешаем на класс ссылки.
3. А почему ссылка осталась без класса? Как её в дальнейшем будешь стилизовать?

2022-08-01 18:00 UTC, andreysgra commented on source/catalog.html
> +            <a href="#">HTML academy</a>
Ссылка на сайт академии.

2022-08-01 18:00 UTC, andreysgra commented on source/catalog.html
> +      </div>
Этот блок собственно для чего? Только для фонового изображения гор? Нехорошо. Здесь логичнее поступить так:
в `catalog-welcome` будет изображение с надписью "sedona" (файл в формате SVG, добавленный через тег `img`). А фоновое изображение гор повесишь на `catalog-welcome`.

2022-08-01 18:00 UTC, andreysgra commented on source/catalog.html
> +        <h2 class="photos-and-videos__title title">Фото и видео</h2>
А тебе не кажется, что этот текст и есть `h1`, а `<h1 class="visually-hidden">Каталог фотографий и видео.</h1>` здесь лишний.

2022-08-01 18:00 UTC, andreysgra commented on source/catalog.html
> +          <img class="photos-list__image" src="/source/img/photos/non-native-expanses.jpg" width="280" height="280"
1. Почему путь к изображению начинается с символа `/`. Браузер не найдёт такой файл. На первом курсе я про такую ошибку уже говорил.
![image](https://user-images.githubusercontent.com/17790771/182205910-ab9fd833-da73-484e-ab26-0817fe99a9b7.png)
2. При чём тут папка source?

Исправь для остальных изображений.

2022-08-01 18:00 UTC, andreysgra commented on source/catalog.html
> +          </div>
А может это кнопка, а не `div`? 😏

2022-08-01 18:00 UTC, andreysgra commented on source/catalog.html
> +          <h2 class="photos-list__title">Неродные просторы</h2>
Заголовок ли это? Это же текст описывающий фотографию.

2022-08-01 18:00 UTC, andreysgra commented on source/catalog.html
> +    <div class="mobile-social">
Почему `mobile-footer`, `mobile-social`? Эти блоки только для мобильной версии, а в планшетной и десктопной версиях будет отдельная разметка для подвала? 😄

2022-08-01 18:00 UTC, andreysgra commented on source/catalog.html
> +      <div class="social-networks networks">
1. Зачем этому блоку целых два класса БЭМ блока?
2. Зачем вообще нужен этот блок-обёртка над списком социальных сетей?

2022-08-01 18:00 UTC, andreysgra commented on source/catalog.html
> +          <li class="social__item item-vk">
Снова вешаешь классы на `li`, а не на ссылку. Стилизовать будешь `li`?

2022-08-01 18:00 UTC, andreysgra commented on source/catalog.html
> +          <li class="social__item item-youtebe">
`item-vk`, `item-telegram` и далее - классы БЭМ блоков. То есть на каждую идентичную ссылку свой БЭМ блок. Сильно жирно получается. Да и вообще, потребуется ли дополнительный класс, чтобы описывать различие между ссылками - большой вопрос.

2022-08-01 18:00 UTC, andreysgra commented on source/catalog.html
> +            </a>
Почему нет скрытого описания у ссылки? Что это и зачем.

2022-08-01 18:00 UTC, andreysgra commented on source/catalog.html
> +        </p>
ТЗ пункт [3.8](https://up.htmlacademy.ru/adaptive/26/project/sedona#sedona-3-8).

2022-08-01 18:00 UTC, andreysgra commented on source/catalog.html
> +  <main class="catalog-container">
Для страницы каталога `catalog-container`, для страницы формы `form-container`, для главной страницы `main-container`. Тебе не кажется такой подход странным? В реальном сайте сотни страниц и что, у каждой будет свой уникальный класс?

2022-08-01 18:00 UTC, andreysgra commented on source/form.html
> +<head class="page-form">
Аналогичный вопрос по названию класса `page-form`.

2022-08-01 18:00 UTC, andreysgra commented on source/form.html
> +<body class="page-form__body">
Везде у `body` класс `page__body`, но почему здесь другой?

2022-08-01 18:00 UTC, andreysgra commented on source/form.html
> +            <a href="#">HTML academy</a>
Ссылки, по аналогии с комментариями для страницы каталога.

2022-08-01 18:00 UTC, andreysgra commented on source/form.html
> +      </div>
Здесь нужно переделать по аналогии с комментарием для страницы каталога.

2022-08-01 18:00 UTC, andreysgra commented on source/catalog.html
> +        <p class="photos-and-videos__text text">Не можете решиться на путешествие из-за курса? Фотографии помогут вам
Классы `title`, `text` с точки зрения ЬЭМ - блоки, то есть независимые структуры. Что это за блоки такие? 🙄 Даже без БЭМ названия классов слишком общие, пространные.

2022-08-01 18:00 UTC, andreysgra commented on source/form.html
> +          <ul class="representation-list representation">
Снова два класса БЭМ блока у одного тега. Зачем?

2022-08-01 18:00 UTC, andreysgra commented on source/form.html
> +            <li class="representation__item middle-name">
Каждый элемент списка отдельный БЭМ блок. Ну зачем? 🙄

2022-08-01 18:00 UTC, andreysgra commented on source/form.html
> +          </ul>
Такие же вопросы по наименованию классов.

2022-08-01 18:00 UTC, andreysgra commented on source/form.html
> +            <li class="impression-list__item impression-item">
`impression-list__item` класс элемента блока `impression-list`. Правильно и логично. `impression-item` класс блока. Зачем класс блока элементу списка?

2022-08-01 18:00 UTC, andreysgra commented on source/form.html
> +          <textarea class="describe-emotions" name="describe-your-emotions" cols="25"
Класс `describe-emotions` - класс БЭМ блока. С какой радости это БЭМ блок?

2022-08-01 18:00 UTC, andreysgra commented on source/form.html
> +        <button class="describe-emotions__button button" type="submit">ОТПРАВИТЬ ОТЗЫВ</button>
Класс `describe-emotions__button` - ошибка именования по БЭМ. Проверить правильность именования можно [здесь](https://yoksel.github.io/html-tree/).

2022-08-01 18:00 UTC, andreysgra commented on source/index.html
> +            <a href="#">HTML academy</a>
Ссылки, по аналогии с комментариями для страницы каталога.

2022-08-01 18:00 UTC, andreysgra commented on source/index.html
> +      </div>
Здесь нужно переделать по аналогии с комментарием для страницы каталога.

2022-08-01 18:00 UTC, andreysgra commented on source/index.html
> +            </ul>
В проекте первого курса точно такой же блок в седоне. Что ж ты опять делаешь странную разметку? 😏

2022-08-01 18:00 UTC, andreysgra commented on source/index.html
> +                <h2 class="advantages-item_title">Жилье</h2>
Почему у класса элемента одно нижнее подчёркивание? Такая ошибка есть и у других классов.

2022-08-01 18:00 UTC, andreysgra commented on source/index.html
> +        <button class="search__find-hotel button">Найти гостиницу</button>
Почему кнопка (да и ещё и без указания типа)?

2022-08-01 18:00 UTC, andreysgra commented on source/index.html
> +        <a href="#">Карта</a>
А для карты разве нужна ссылка? Там, как мы видим, изображение. Его почему-то у тебя нет.

2022-08-04 08:39 UTC, andreysgra requested changes

2022-08-04 08:39 UTC, andreysgra commented on source/catalog.html
> +              <span class="visually-hidden">Сайт HTML академии</span>
А зачем текст в ссылках, который присутствует в явном виде, оборачивать в `span` с классом `visually-hidden`? 🙄

2022-08-04 08:39 UTC, andreysgra commented on source/catalog.html
> +          </li>
Ещё раз, более детально разберём именование классов по БЭМ, так как я вижу, что оно тебе не до конца понятно.

Есть список ссылок с классом `main-nav-list`. По БЭМ этот класс описывает блок, то есть обособленную, самостоятельную структуру. В данном случае вполне логично и имеет право быть.

Элементу списка `li` ты добавил два класса `nav-item` и `item`. Здесь две проблемы:
1. Элемент списка не может существовать вне самого списка, значит это несамостоятельная структура и у неё не может быть класс блока. А раз это не блок, то это элемент блока `main-nav-list`, соответственно имя класса нужно строить от него: `main-nav-list__item`.
2. Даже если бы тут можно было использовать класс блока, то зачем одному тегу целых **два** класса блока `nav-item` и `item`? Самостоятельная сущность под двумя названиями. Зачем?

Такая же беда с классами ссылки: два класса блока `item-link` и `link-main`. Как я уже писал выше, тегу никогда не дают два класса БЭМ блока, так как никакого практического и логического смысла в этом нет. Теперь вопрос: может ли данная ссылка быть БЭМ блоком? Если такой вид оформления используется только в верхнем меню (а в этом проекте так оно и есть), то смысла делать из ссылки БЭМ блок нет, так как нет повторной используемости. Выходит, что это БЭМ элемент списка `main-nav-list` и класс у него должен быть `main-nav-list__link`.

2022-08-04 08:39 UTC, andreysgra commented on source/catalog.html
> +    </div>
`div` с классом БЭМ блока `photos-and-videos`, а внутри него сплошные БЭМ блоки: `photos-and-videos-title`, `photos-and-videos-text`. Почему не БЭМ элементы?

2022-08-04 08:39 UTC, andreysgra commented on source/catalog.html
> +          <button class="reactions button" type="button">
Два класса БЭМ блока `reactions` и `button`.

2022-08-04 08:39 UTC, andreysgra commented on source/catalog.html
> +            </span>
Для чего SVG обёрнуто в `span`? Есть ли в этом какой-то практический смысл?

2022-08-04 08:39 UTC, andreysgra commented on source/catalog.html
> +          <span class="reactions-count">1350</span>
`reactions-count` - класс БЭМ блока. Тут просто текст рядом с кнопкой.

2022-08-04 08:39 UTC, andreysgra commented on source/catalog.html
> +        очередной раз!</p>
Снова классы блока. Местами ты называешь классы правильно. Взять к примеру список `photos-list`. Здесь же зачем-то каждый параграф выделяешь в отдельный блок.

2022-08-04 08:39 UTC, andreysgra commented on source/catalog.html
> +      <div class="social-networks networks">
1. Два класса БЭМ: `social-networks`, `networks`.
2. Думаю, что этот `div` здесь вообще лишний.

2022-08-04 08:39 UTC, andreysgra commented on source/catalog.html
> +        <ul class="networks__list list">
Вот здесь лучше использовать класс `social-networks` (`div` с этим классом, как я предлагаю, нужно удалить) и название классов вложенных в него тегов строить от него.

2022-08-04 08:39 UTC, andreysgra commented on source/catalog.html
> +          <li class="list__item item">
Класс `item` здесь ни к чему.

2022-08-04 08:39 UTC, andreysgra commented on source/catalog.html
> +            <a class="item__social-active item-youtebe" href="https://www.youtube.com/user/htmlacademyru">
Если в элементах интерфейса есть небольшое различие, то оно описывается в классе модификатора (класс модифицирует какое-то базовое свойство). Поэтому ссылкам, наряду с классом элемента `social-networks__link` (название `item__social-active` совсем не годится, так как во-первых строится от непонятного блока `item`, которого в принципе быть здесь не должно, а вторых название никак не отражает суть тега, к которому применяется) нужно будет добавить и класс модификатора. Для ссылки "VK" будет называться `social-networks__link--vk`, для остальных по аналогии.

2022-08-04 08:39 UTC, andreysgra commented on source/form.html
> +    <section class="form">
Нет закрывающего тега е этой секции. Ошибка валидации:
![image](https://user-images.githubusercontent.com/17790771/182795328-ae34532c-53f7-424e-806e-264a3ab04f9e.png)

И сразу напрашивается вопрос: а так ли секция здесь необходима? У тебя она служит всего лишь обёрткой над тегом `form`. Если секцию будешь удалять, то удали и заголовок "Форма отзыва" за ненадобностью.

2022-08-04 08:39 UTC, andreysgra commented on source/form.html
> +        вами достопримечательностях</p>
Аналогично замечанию по схожему блоку на странице каталога (классы БЭМ блоков).

2022-08-04 08:39 UTC, andreysgra commented on source/form.html
> +        <fieldset class="form-response">
У формы класс блока `form-response` и у группы полей точно такой же класс. Не смущает? 😏 Правильно будет использовать класс БЭМ элемента для группы полей.

2022-08-04 08:39 UTC, andreysgra commented on source/form.html
> +          <ul class="representation-list representation">
[Это](https://github.com/htmlacademy-adaptive/2056523-sedona-26/pull/2#discussion_r934769034) замечание не исправлено.

2022-08-04 08:39 UTC, andreysgra commented on source/form.html
> +            <li class="representation__item middle-name">
[Это](https://github.com/htmlacademy-adaptive/2056523-sedona-26/pull/2#discussion_r934769721) замечание не исправлено.

2022-08-04 08:39 UTC, andreysgra commented on source/form.html
> +        <fieldset class="form-contact">
Зачем группе полей класс БЭМ блока?

2022-08-04 08:39 UTC, andreysgra commented on source/form.html
> +          <legend class="form-contact__title">Контактная информация:</legend>
Легенды в этой форме имеют одинаковое оформление, не так ли? Зачем же ты им присвоил разные классы?

2022-08-04 08:39 UTC, andreysgra commented on source/form.html
> +          </ul>
[Это](https://github.com/htmlacademy-adaptive/2056523-sedona-26/pull/2#discussion_r934770397) замечание не исправлено.

2022-08-04 08:39 UTC, andreysgra commented on source/form.html
> +            <li class="impression-list__item impression-item">
[Это](https://github.com/htmlacademy-adaptive/2056523-sedona-26/pull/2#discussion_r934771745) замечание не исправлено.

2022-08-04 08:39 UTC, andreysgra commented on source/form.html
> +          <textarea class="describe-emotions" name="describe-your-emotions" cols="25"
[Это](https://github.com/htmlacademy-adaptive/2056523-sedona-26/pull/2#discussion_r934772809) замечание не исправлено.

2022-08-04 08:39 UTC, andreysgra commented on source/form.html
> +        <button class="describe-emotions__button button" type="submit">ОТПРАВИТЬ ОТЗЫВ</button>
[Это](https://github.com/htmlacademy-adaptive/2056523-sedona-26/pull/2#discussion_r934773656) замечание не исправлено.

2022-08-04 08:39 UTC, andreysgra commented on source/form.html
> +  </div>
Здесь, для отличий блоков лучше использовать классы-модификаторы. Общий класс окон `modal-container`, а класс модификатора для окна ошибки `modal-container--error`, для окна успешной отправки `modal-container--sent`.

2022-08-04 08:39 UTC, andreysgra commented on source/form.html
> +    <p class="modal-description">Проверьте поля, выделенные красным, скорее всего вы забыли их заполнить</p>
Классы БЭМ блоков.

2022-08-04 08:39 UTC, andreysgra commented on source/form.html
> +    <button class="modal-button button" type="button">OK</button>
Тебе не кажется, что в этих окнах кнопки оформлены так же, как и остальные кнопки сайта? Зачем их выделять в отдельный блок `modal-button`? Про абсурдность использования двух классов блока я писал выше.

2022-08-04 08:39 UTC, andreysgra commented on source/index.html
> +        <p class="presentation-text">Рассмотрим 5 причин, по которым Седона круче, чем гранд каньон!</p>
Аналогично замечанию по схожему блоку на странице каталога (классы БЭМ блоков).

2022-08-04 08:39 UTC, andreysgra commented on source/index.html
> +        <li class="advantages-item">
`advantages-item` класс БЭМ блока, но тут БЭМ элемент.

2022-08-04 08:39 UTC, andreysgra commented on source/index.html
> +          <img class="advantages-image" width="520" height="260" src="img/advantages/town-of-sedona.jpg"
Сплошные классы БЭМ элементов 😥.

2022-08-04 08:39 UTC, andreysgra commented on source/index.html
> +            </li>
Сплошные классы БЭМ элементов 😥.

2022-08-04 08:39 UTC, andreysgra commented on source/index.html
> +            <h2 class="item-title">НАСТОЯЩИЙ ГОРОДОК</h2>
У секции есть заголовок второго уровня "Наши преимущества". В каждой карточке перечисляются эти преимущества, а значит, чтобы соблюсти иерархию заголовков в преимуществах нужно использовать заголовки третьего уровня.

2022-08-04 08:39 UTC, andreysgra commented on source/index.html
> +              <h3 class="nested-item-title">Жилье</h3>
Здесь уже будет заголовок четвёртого уровня.

2022-08-04 08:39 UTC, andreysgra commented on source/index.html
> +        <button class="search__find-hotel button" type="submit">Найти гостиницу</button>
[Здесь](https://github.com/htmlacademy-adaptive/2056523-sedona-26/pull/2#discussion_r934781925) я спрашивал "почему кнопка"? Тип `submit` бывает у кнопок только тех, которые отправляют данные формы. Формы здесь нет и кнопка не форме (но и не кнопка это).

2022-08-05 14:59 UTC, andreysgra requested changes
Сейчас значительно лучше и виден прогресс, молодец. Но тем не менее есть ещё над чем поработать 😏.

2022-08-05 14:59 UTC, andreysgra commented on source/catalog.html
> +      <p class="videos__descriotion">Смотрите видеопрезентацию и скорее за билетами, пока они не подорожали в
```suggestion
      <p class="videos__description">Смотрите видеопрезентацию и скорее за билетами, пока они не подорожали в
```

2022-08-05 14:59 UTC, andreysgra commented on source/catalog.html
> +          <span class="reactions-count">143</span>
Логичнее, если этот `span` будет не блоком, а элементом с классом `photos-list__reactions-count`. Нет никакой необходимости из этого текста делать блок. Здесь нет независимости компонента. Собственно [об этом](https://github.com/htmlacademy-adaptive/2056523-sedona-26/pull/2#discussion_r937446859) я писал ранее.

2022-08-05 14:59 UTC, andreysgra commented on source/catalog.html
> +            <svg class="photos-list__like" width="22" height="20" viewBox="0 0 22 20" fill="none"
Это изображение кнопки и не более того, но класс `photos-list__like` не даёт представления об этом. А вот если бы класс назывался `photos-list__reactions-icon`, то сразу было бы понятно, что это за элемент (кнопка имеет класс `photos-list__reactions`, а класс `photos-list__reactions-icon` иконки прямо говорит об этом - это иконка кнопки `photos-list__reactions`).

2022-08-05 14:59 UTC, andreysgra commented on source/catalog.html
> +          <b class="reactions-count">254</b>
В других случаях использован тег `span` для разметки этого текста, а здесь почему-то `b`.

2022-08-05 14:59 UTC, andreysgra commented on source/form.html
> +    </div>
Если внимательно приглядеться, то мы увидим идентичность этих блоков на страницах сайта:
![image](https://user-images.githubusercontent.com/17790771/183099180-87eb9916-8642-4ea2-90ec-4fc036fbaf44.png)
![image](https://user-images.githubusercontent.com/17790771/183099230-085321c2-7d78-4591-8762-0cd4d33d0458.png)
![image](https://user-images.githubusercontent.com/17790771/183099299-2849282e-bdc4-4bad-8b66-855a64b3fbc5.png)

Если блоки имеют одинаковое оформление, то какой смысл именовать в них классы по разному, подчёркивая принадлежность к конкретной странице: `photos-and-videos`, `leave-comment`, `presentation`. В реальном сайте сотни страниц и при таком не универсальном подходе придётся для каждой страницы придумывать свои классы и дублировать стили. Нужно подумать над общим названием класса, какое предназначение имеет этот блок и переименовать на всех страницах (соответственно нужно будет скорректировать названия классов элементов этого блока).

2022-08-05 14:59 UTC, andreysgra commented on source/form.html
> +      <fieldset class="be-provided">
Ну здесь уже ранее озвученная проблема: мало того, что `fieldset` имеет класс блока, так ещё каждый `fieldset` формы со своим уникальным классом. Подход неверный. В прошлый раз [я писал](https://github.com/htmlacademy-adaptive/2056523-sedona-26/pull/2#discussion_r937475437) об этом (третье предложение комментария).

Согласно этого замечания внеси изменения во все fieldset` и элементы, которые в них вложены.

2022-08-05 14:59 UTC, andreysgra commented on source/form.html
> +          <li class="be-provided__middle-name">
У тебя каждый элемент списка имеет уникальный класс. Один `li` чем-то отличается в корне от другого? Зачем ему такая привилегия?

2022-08-05 14:59 UTC, andreysgra commented on source/index.html
> +            <li class="advantages-nested-item">
```suggestion
            <li class="advantages__nested-item">
```

2022-08-05 14:59 UTC, andreysgra commented on source/index.html
> +          </ul>
А для чего причины №3 - №5 выделять в отдельный вложенный список? Это элементы списка `advantages__list`. Каждая отдельная причина это `li` с классом `advantages__item`.

2022-08-05 14:59 UTC, andreysgra commented on source/index.html
> +            <p class="wrapper-advantages__numder">— №1 —</p>
```suggestion
            <p class="wrapper-advantages__number">— №1 —</p>
```
Исправь и в остальных причинах.

2022-08-05 15:31 UTC, Gri-F commented on source/catalog.html
> +          <span class="reactions-count">1350</span>
я просто не понял , что нужно сделать элементом)

2022-08-05 18:45 UTC, andreysgra approved these changes

2022-08-05 18:45 UTC, andreysgra commented on source/index.html
> +        <li class="advantages__item-item">
```suggestion
        <li class="advantages__item">
```

2022-08-05 18:48 UTC, merged