Стилизация
htmlacademy-adaptive/2056523-sedona-26 pull request #3
Opened 2022-08-11 12:45 UTC by Gri-F

2022-08-12 06:52 UTC, andreysgra requested changes
Свойство `font-family` наследуемой, поэтому достаточно описать его один раз в классе `.page` и не указывать всякий раз для каждого класса (исключения составляют только кнопки и элементы формы).

2022-08-12 06:52 UTC, andreysgra commented on source/catalog.html
> +      </svg>
1. Зачем извлекать из макета отдельные части изображения intro-triangle.svg?
2. Зачем в разметку добавлять это фоновое изображение?

2022-08-12 06:52 UTC, andreysgra commented on source/form.html
> +      </svg>
Здесь тоже самое, что и сказанное выше.

2022-08-12 06:52 UTC, andreysgra commented on source/form.html
>            </li>
Не понимаю, зачем для label и input отдельный элемент списка? Список это не какой-то универсальный контейнер для построения сеток. Это семантический элемент разметки, в котором идёт перечисление схожих по смыслу сущностей.

Есть группа полей формы в блоке "представьтесь". Можно их разметить с помощью списка и тогда список будет выглядеть так:
- имя;
- фамилия;
- отчество.

А у тебя список получился такой:
- имя;
- Пётр;
- фамилия;
- Пустота;
- отчество;
- Викторович.

Предыдущая разметка у тебя была правильной.

2022-08-12 06:52 UTC, andreysgra commented on source/form.html
> +              placeholder="Введите телефон" required>
Тоже самое и в этом блоке и остальных: не разделяй на отдельные `li` элементы `label` и `input`. Должно быть так:
```
<li>
  <label></label>
  <input>
</li>
```

2022-08-12 06:52 UTC, andreysgra commented on source/index.html
> +        </svg>
А так ли нужно это изображение вставлять в разметку? Почему не фоновое изображение?

2022-08-12 06:52 UTC, andreysgra commented on source/index.html
> +      </svg>
Также не нужно изображение intro-triangle.svg в разметке.

2022-08-12 06:52 UTC, andreysgra commented on source/index.html
> +          <svg class="advantages__icon" width="80" height="80" viewBox="0 0 80 80" fill="none"
Эти иконки изображения декоративные. Не нужно их добавлять в разметку.
![image](https://user-images.githubusercontent.com/17790771/184297552-33a09052-9d01-40c5-b996-17753867e2e5.png)

2022-08-12 06:52 UTC, andreysgra commented on source/index.html
> +        <li class="advantages__item advantages__item-color">
В классе `advantages__item-color` ты изменяешь цвет блока, то есть модифицируешь какое-то базовое свойство. Стало быть нужен класс модификатора, а не элемента. Например `advantages__item--color-gray`.

2022-08-12 06:52 UTC, andreysgra commented on source/less/blocks/main-container.less
> +  background-image: url("../../img/background/sedona-mountains-mobile.jpg");
```suggestion
  background-image: url("../img/background/sedona-mountains-mobile.jpg");
```
Неплохо бы уже запомнить, как правильно записываются относительные пути.

2022-08-12 06:52 UTC, andreysgra commented on source/less/blocks/main-footer.less
> +}
Давай в этом задании не заниматься построением сеток. Это задание не про них. У нас подход "mobile first", посмотри, как выглядит этот блок в мобильной версии.

Все свойства, которые отвечают за изменение положения блоков (построение сетки) убери. Вернёмся к ним в следующем задании.

2022-08-12 06:52 UTC, andreysgra commented on source/less/blocks/main-header.less
> +  right: 45%;
Почему именно 45%?

2022-08-12 06:52 UTC, andreysgra commented on source/less/blocks/main-nav-list.less
> +}
Свойства отвечающие за построение сетки удаляем.

2022-08-12 06:52 UTC, andreysgra commented on source/less/blocks/modal-container.less
> +  height: 280px;
Свойства отвечающие за построение сетки удаляем.

2022-08-12 06:52 UTC, andreysgra commented on source/less/blocks/page.less
> +}
Класс `visually-hidden` служебный и никакого отношения ни к блоку `page`, ни к БЭМ, не имеет. Служебные классы можно вынести в отдельный файл global.less, который будет находиться в той же папке, что и style.less.

2022-08-12 06:52 UTC, andreysgra commented on source/less/blocks/recall-form.less
> +.recall-form-question {
```suggestion
.recall-form__question {
```
Это класс элемента, а не блока.

2022-08-12 06:52 UTC, andreysgra commented on source/less/blocks/recall-form.less
> +.recall-form-data-input {
```suggestion
.recall-form__data-input {
```
Это класс элемента, а не блока.

2022-08-12 06:52 UTC, andreysgra commented on source/less/blocks/recall-form.less
> +.recall-form-image {
```suggestion
.recall-form__image {
```
Это класс элемента, а не блока.

2022-08-12 06:52 UTC, andreysgra commented on source/less/blocks/recall-form.less
> +.recall-form-data-input {
```suggestion
.recall-form__data-input {
```
Это класс элемента, а не блока. Ну и вообще, класс описан в строке 41.

2022-08-12 06:52 UTC, andreysgra commented on source/less/blocks/recall-form.less
> +.choice-of-impression {
Класс вообще не из этой оперы (файл называется recall-form.less).

2022-08-12 06:52 UTC, andreysgra commented on source/less/blocks/search.less
> +.button {
Нужно перенести в соответствующий файл.

2022-08-15 09:00 UTC, Gri-F commented on source/index.html
> +        </svg>
я думаю да, мы ему цвет будем менять при наведении

2022-08-15 09:06 UTC, gri-f commented on source/index.html
> +          <svg class="advantages__icon" width="80" height="80" viewBox="0 0 80 80" fill="none"
я тогда не понимаю как, у нас 3 разных изображения , а класс у всех 1, каждому элементу еще по разному классу добавить и потом к ним уже добавить эти элементы? , или пока не добавлять , а потом когда пройдем спрайты уже через них добавить?

2022-08-15 09:32 UTC, Gri-F commented on source/less/blocks/main-container.less
> +  background-image: url("../../img/background/sedona-mountains-mobile.jpg");
Андрей мне пути сам VS code подсказывает как писать , у меня есть папка "less"  в ней папка  "block" я выхожу из папки "block" в папку "less" и когда я поднимаюсь еще на уровень выше тогда я вижу что есть другие папки (если не поднимаюсь то другие папки не вижу) и потом я уже иду в них, да я вижу у меня постоянно замечания с путями, но мне так VS code подсказывает (и подсвечивает папки , вот у меня и получается такой путь ((( )

2022-08-15 09:41 UTC, Gri-F commented on source/less/blocks/main-header.less
> +  right: 45%;
я логотип убрал из "main-header" переместил в "main-nav" и все равно не могу выровнять по центру,  сталю значения top: 0 ; right: 50%; и все равно он не встает по центру, я его уже и в список с ссылками пробовал перемещать , тоже не получается поставить по центру , подскажи на что обратить внимание , чтобы получилось по центру

2022-08-15 10:37 UTC, Gri-F commented on source/less/blocks/search.less
> +.button {
я здесь не понял куда можно перенести, я все стили из button перенес в "search__find-hotel"

2022-08-15 18:44 UTC, andreysgra commented on source/index.html
> +        </svg>
При наведении на эту кнопку изменяется `opacity`, а для этого нет необходимости добавлять svg в разметку.

2022-08-15 18:44 UTC, andreysgra commented on source/index.html
> +          <svg class="advantages__icon" width="80" height="80" viewBox="0 0 80 80" fill="none"
Если изображение фоновое, то придётся добавлять классы-модификаторы. Да, чтобы это не делать, можно было бы использовать svg в разметке (учитывая использование svg спрайта), но на защите могут к этому моменту придраться.

2022-08-15 19:01 UTC, andreysgra commented on source/less/blocks/main-container.less
> +  background-image: url("../../img/background/sedona-mountains-mobile.jpg");
VS code показывает относительные пути в соответствии с файловой структуры проекта, но он ничего не знает о том, что файлы препроцессора .less будут преобразованы в один файл style.css.

Браузер разбирает относительные пути относительно файла, в котором они написаны. В данном случае это файл style.less. У нас файловая структура сайта (**не проекта!**) такая:
```bash
.                 # корневой каталог сайта
├── fonts/        # каталог шрифтов
├── img/          # каталог растровых и векторных изображений
├── css/          # каталог файлов стилей
│    └──  styles.css
└── index.html    # файл разметки страницы
```
Чтобы браузер мог найти путь к файлу изображения, который указан в styles.css ему нужно перейти на один уровень вверх относительно файла styles.css и тогда он сможет найти каталог img, а если в относительном пути указать два перехода наверх `../../`, то мы окажемся за пределами корневого каталога сайта (что в реальности невозможно из-за настроек сервера) и указанный путь будет неверным.

2022-08-15 19:15 UTC, andreysgra commented on source/less/blocks/main-header.less
> +  right: 45%;
Я могу подсказать на что обратить внимание: на принцип, по которому рассчитывается положение абсолютно позиционированного элемента. Свойство `left` описывает положение верхней левой координаты элемента, а свойство `right` описывает положение верхней правой координаты элемента. Это не точка в центре элемента, поэтому чем больше ширина элемента, тем дальше он будет находиться относительно центра того блока, по которому мы его позиционируем.

Для компенсации этого есть довольно древний способ (но есть и более современный): отрицательное значение `margin-left` равное половине ширины позиционируемого элемента (при этом `left` равно `50%`).

2022-08-15 19:25 UTC, andreysgra commented on source/less/blocks/global.less
> +.visually-hidden {
Пожалуйста, чуточку внимательнее читай мои комментарии. [Здесь](https://github.com/htmlacademy-adaptive/2056523-sedona-26/pull/3#discussion_r944160543) я писал _"который будет находиться в той же папке, что и style.less"_. Чего же ты поместил его в папку blocks?

2022-08-15 19:25 UTC, andreysgra commented on source/less/blocks/page.less
> +  padding: 0 40px;
Класс `.page` применён к тегу `html`. Зачем этому тегу `max-width` и `padding`? Не нужно. Пусть пока не начали строить сетку сайта контент растягивается на всю ширину страницы.

2022-08-15 19:25 UTC, andreysgra commented on source/less/blocks/search.less
> +.button {
По БЭМ класс `.button` описывает блок, а значит нужно перенести его в файл button.less.

2022-08-15 19:27 UTC, andreysgra approved these changes
В целом всё хорошо, поэтому задание принимаю несмотря на два небольших недочёта.

2022-08-15 19:28 UTC, merged

2022-08-16 17:36 UTC, gri-f commented on source/less/blocks/main-container.less
> +  background-image: url("../../img/background/sedona-mountains-mobile.jpg");
нам сказали используйте файл Less , я от него и отталкиваюсь, вот в этом и ошибка, я думаю что стили будут браться и этих файлов и от них отталкиваюсь(((